# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dataNode_apiGateway_pb2 as dataNode__apiGateway__pb2


class DataNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteFile = channel.unary_unary(
                '/DataNodeService/WriteFile',
                request_serializer=dataNode__apiGateway__pb2.WriteFileRequestData.SerializeToString,
                response_deserializer=dataNode__apiGateway__pb2.WriteFileResponseData.FromString,
                )
        self.ReadFile = channel.unary_unary(
                '/DataNodeService/ReadFile',
                request_serializer=dataNode__apiGateway__pb2.ReadFileRequestData.SerializeToString,
                response_deserializer=dataNode__apiGateway__pb2.ReadFileResponseData.FromString,
                )


class DataNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=dataNode__apiGateway__pb2.WriteFileRequestData.FromString,
                    response_serializer=dataNode__apiGateway__pb2.WriteFileResponseData.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=dataNode__apiGateway__pb2.ReadFileRequestData.FromString,
                    response_serializer=dataNode__apiGateway__pb2.ReadFileResponseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataNodeService/WriteFile',
            dataNode__apiGateway__pb2.WriteFileRequestData.SerializeToString,
            dataNode__apiGateway__pb2.WriteFileResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataNodeService/ReadFile',
            dataNode__apiGateway__pb2.ReadFileRequestData.SerializeToString,
            dataNode__apiGateway__pb2.ReadFileResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
