# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataNode-dataNode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61taNode-dataNode.proto\"D\n\rReplicateFile\x12\x0e\n\x06\x66older\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\tfile_data\x18\x03 \x01(\x0c\"+\n\x15ReplicateFileResponse\x12\x12\n\nreplicated\x18\x01 \x01(\t2G\n\x10ReplicateService\x12\x33\n\tWriteFile\x12\x0e.ReplicateFile\x1a\x16.ReplicateFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataNode_dataNode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REPLICATEFILE']._serialized_start=27
  _globals['_REPLICATEFILE']._serialized_end=95
  _globals['_REPLICATEFILERESPONSE']._serialized_start=97
  _globals['_REPLICATEFILERESPONSE']._serialized_end=140
  _globals['_REPLICATESERVICE']._serialized_start=142
  _globals['_REPLICATESERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
