# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dataNode_dataNode_pb2 as dataNode__dataNode__pb2


class ReplicateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteFile = channel.unary_unary(
                '/ReplicateService/WriteFile',
                request_serializer=dataNode__dataNode__pb2.ReplicateFile.SerializeToString,
                response_deserializer=dataNode__dataNode__pb2.ReplicateFileResponse.FromString,
                )


class ReplicateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=dataNode__dataNode__pb2.ReplicateFile.FromString,
                    response_serializer=dataNode__dataNode__pb2.ReplicateFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReplicateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReplicateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ReplicateService/WriteFile',
            dataNode__dataNode__pb2.ReplicateFile.SerializeToString,
            dataNode__dataNode__pb2.ReplicateFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
