# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiGateway-nameNode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61piGateway-nameNode.proto\"4\n\x10WriteFileRequest\x12\x0e\n\x06\x66older\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"A\n\x11WriteFileResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x61ta_node_addresses\x18\x02 \x03(\t\"3\n\x0fReadFileRequest\x12\x0e\n\x06\x66older\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"@\n\x10ReadFileResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x61ta_node_addresses\x18\x02 \x03(\t\"\x12\n\x10ListFilesRequest\"&\n\x11ListFilesResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t2\xaa\x01\n\x0fNameNodeService\x12\x32\n\tWriteFile\x12\x11.WriteFileRequest\x1a\x12.WriteFileResponse\x12/\n\x08ReadFile\x12\x10.ReadFileRequest\x1a\x11.ReadFileResponse\x12\x32\n\tListFiles\x12\x11.ListFilesRequest\x1a\x12.ListFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apiGateway_nameNode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WRITEFILEREQUEST']._serialized_start=29
  _globals['_WRITEFILEREQUEST']._serialized_end=81
  _globals['_WRITEFILERESPONSE']._serialized_start=83
  _globals['_WRITEFILERESPONSE']._serialized_end=148
  _globals['_READFILEREQUEST']._serialized_start=150
  _globals['_READFILEREQUEST']._serialized_end=201
  _globals['_READFILERESPONSE']._serialized_start=203
  _globals['_READFILERESPONSE']._serialized_end=267
  _globals['_LISTFILESREQUEST']._serialized_start=269
  _globals['_LISTFILESREQUEST']._serialized_end=287
  _globals['_LISTFILESRESPONSE']._serialized_start=289
  _globals['_LISTFILESRESPONSE']._serialized_end=327
  _globals['_NAMENODESERVICE']._serialized_start=330
  _globals['_NAMENODESERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
