# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiGateway-dataNode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61piGateway-dataNode.proto\x1a\x1egoogle/protobuf/wrappers.proto\"]\n\tWriteFile\x12\x0e\n\x06\x66older\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12.\n\tfile_data\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.BytesValue\"A\n\x11WriteFileResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x61ta_node_addresses\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apiGateway_dataNode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WRITEFILE']._serialized_start=61
  _globals['_WRITEFILE']._serialized_end=154
  _globals['_WRITEFILERESPONSE']._serialized_start=156
  _globals['_WRITEFILERESPONSE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
